#Data

In [1]:
import requests
import pandas as pd

In [2]:
df=pd.read_csv('/content/digikala_sentiment.csv')

In [3]:
# df[(df['Suggestion']==3)& (df['Score']>70)]
# df[(df['Suggestion']==2)]


Text  Score  Suggestion
32                               موبایل بسیار خوبی است     100           2
48    بعد از دو سال گوشیم کند شد   و ریست می شد مرتب...     96           2
60    من دو سال بود داشتم از چی پی اس راضی نبودم اما...     48           2
85    من برای کارای دانشجویی و سبک گرفتم کیفیت ساخت ...     84           2
91    تبلت من بعد از سه روز بلا استفاده بودن دیگر رو...     60           2
...                                                 ...    ...         ...
3238  جنسش عالی و با کیفیته حیف ک طرحش زیاد قشنگ نیس...     80           2
3245        این مدل تحت لیسانس فرانسه در چین تولید شده      68           2
3248  کلمه Tefal برگرفته از ترکیب دو کلمه Teflon  و ...    100           2
3249  من این کالا رو حدود دو هفته هست که خریدم  البت...     64           2
3256  کیفت ساختش خوبه تنوعش هم خوبه   فقط مشکلش اینه...     84           2

[419 rows x 3 columns]

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3261 entries, 0 to 3260
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Text        3261 non-null   object
 1   Score       3261 non-null   int64 
 2   Suggestion  3261 non-null   int64 
dtypes: int64(2), object(1)
memory usage: 76.6+ KB


Score  Suggestion
count  3261.000000  3261.00000
mean     74.719411     1.41061
std      21.514015     0.72408
min       0.000000     1.00000
25%      60.000000     1.00000
50%      80.000000     1.00000
75%      92.000000     2.00000
max     100.000000     3.00000

In [ ]:
df.isnull().sum()


Text          0
Score         0
Suggestion    0
dtype: int64

##Datapreprocessing

In [4]:
!pip install hazm


In [5]:
from hazm import Normalizer, word_tokenize, stopwords_list, Stemmer, Lemmatizer
import re
Normalizer_object = Normalizer()
word_tokenize_object=word_tokenize
stopwords = stopwords_list()

def CleanText(text):
  text=Normalizer_object.normalize(text)
  text=word_tokenize_object(text)
  text=' '.join([word for word in text if word not in stopwords])
  return text

stemmer = Stemmer()
lemmatizer = Lemmatizer()
def clean_text_rich(text):
    # حذف ایموجی و لینک
    text = re.sub(r"http\S+|www\S+|https\S+", '', text)
    text = re.sub(r"[^\w\s]", '', text)  # حذف علائم نگارشی
    text = Normalizer_object.normalize(text)
    tokens = word_tokenize(text)
    tokens = [lemmatizer.lemmatize(w) for w in tokens if len(w) > 2]
    return " ".join(tokens)

In [6]:
df["cleanedText"]=df["Text"].apply(clean_text_rich);
df

Text  Score  Suggestion  \
0     این اولین تجربه من برای خرید ایفون هست   امروز...    100           1   
1                        خرید این محصول رو توصیه میکنم      84           1   
2     1 ساله این گوشی رو دارم   هیچ نقطه ضعفی ازش ند...     60           1   
3     سلام خدمت دوستان این گوشی از همه نظر عالی  کیف...     96           1   
4     سلام دوستانی که نگران شکستن صفحه نمایش هستند ا...     92           1   
...                                                 ...    ...         ...   
3256  کیفت ساختش خوبه تنوعش هم خوبه   فقط مشکلش اینه...     84           2   
3257           خیلی خوب و به درد بخوره و اندازشم عالیه     100           1   
3258  عالیه خیلی دوسش دارم قیمتش یه کم زیاده ولی به ...    100           1   
3259  من این مینی فرز رو از دیحیکالا سفارش دادم و به...     84           1   
3260  بعد از چند دقیقه که باهاش کار کنی سریع داغ میش...     48           3   

                                            cleanedText  
0     این اولین تجربه برای خرید ایفون هست امروز دستم...  
1                           خرید این محصول توصیه کرد#کن  
2     ساله این گوشید#گوش داشت#دار هیچ نقطه ضعفی ازش ...  
3     سلام خدمت دوستان این گوشید#گوش همه نظر عالی کی...  
4     سلام دوستانی نگران شکستن صفحه نمایش #هست این ب...  
...                                                 ...  
3256  کیف ساخت خوبه تنوع خوبه فقط مشکل اینه پیچ‌گوشت...  
3257                     خیلی خوب درد بخوره انداز عالیه  
3258  عالیه خیلی دوس داشت#دار قیمت زیاده ولی نظر ارز...  
3259  این مینی فرز دیحیکالا سفارش داد#ده دستم رسید ف...  
3260  بعد چند دقیقه با کار کرد#کن سریع داغ میشه حتی ...  

[3261 rows x 4 columns]

In [ ]:
# def label_sentimate(score):
#   if score<40:
#     return -1
#   elif score>60:
#     return 1
#   else:
#     return 0

# df["Sentimate"]=df.Score.apply(label_sentimate)
# df.head()

Text  Score  Suggestion  \
0  این اولین تجربه من برای خرید ایفون هست   امروز...    100           1   
1                     خرید این محصول رو توصیه میکنم      84           1   
2  1 ساله این گوشی رو دارم   هیچ نقطه ضعفی ازش ند...     60           1   
3  سلام خدمت دوستان این گوشی از همه نظر عالی  کیف...     96           1   
4  سلام دوستانی که نگران شکستن صفحه نمایش هستند ا...     92           1   

                                         cleanedText  Sentimate  
0  تجربه خرید ایفون هست امروز ب دستم رسیده اسم طل...          1  
1                                   خرید محصول توصیه          1  
2                    ۱ گوشی دارم نقطه ضعفی ازش ندیدم          0  
3  سلام خدمت دوستان گوشی کیفیت ساخت سرعت کیفیت صد...          1  
4  سلام دوستانی نگران شکستن صفحه نمایش بدونند صفح...          1

In [8]:
data=df.copy()
# data=data.drop(["Text","Score","Sentimate"],axis=1)

In [9]:
data['Suggestion'].value_counts()

Suggestion
1    2382
3     460
2     419
Name: count, dtype: int64

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer=TfidfVectorizer(ngram_range=(1,2), max_features=3000,max_df=0.85, min_df=5)
vectorized_Text=vectorizer.fit_transform(data['cleanedText'])

In [ ]:
vectorized_Text.toarray()[0]


array([0., 0., 0., ..., 0., 0., 0.])

##Train Test

In [42]:
from sklearn.model_selection import train_test_split

X=vectorized_Text
y=data['Suggestion']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [43]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X, y)


In [13]:
y_test.value_counts(normalize=True)

Suggestion
1    0.730475
3    0.140888
2    0.128637
Name: proportion, dtype: float64

#Model

In [44]:
from sklearn.naive_bayes import MultinomialNB

# Mn=MultinomialNB()
# Mn.fit(X_train,y_train)

from sklearn.linear_model import LogisticRegression
Mn=LogisticRegression(class_weight='balanced')
Mn.fit(X_train,y_train)

LogisticRegression(class_weight='balanced')

In [45]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(Mn, X_train, y_train, cv=5))

[0.78321678 0.87263821 0.86284115 0.88313506 0.89713086]


In [46]:
y_pred=Mn.predict(X_test)

In [ ]:
# y_test.value_counts()

Suggestion
1    477
3     92
2     84
Name: count, dtype: int64

##Score

In [ ]:
# pd.DataFrame(y_pred).value_counts()

0 
 1    436
 0    169
-1     48
Name: count, dtype: int64

In [47]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# گزارش ارزیابی مدل
print(classification_report(y_test, y_pred))

# ماتریس آشوب
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.98      0.88      0.93       477
           2       0.67      0.94      0.78        84
           3       0.81      0.95      0.87        92

    accuracy                           0.90       653
   macro avg       0.82      0.92      0.86       653
weighted avg       0.92      0.90      0.90       653

[[421  38  18]
 [  3  79   2]
 [  4   1  87]]
Accuracy: 0.8989280245022971


In [ ]:

df[df['Score']<20]['Score'].value_counts()

Score
0     37
16    13
4     10
8      8
12     8
10     1
Name: count, dtype: int64

In [ ]:

X_train.toarray

<bound method _cs_matrix.toarray of <2608x11394 sparse matrix of type '<class 'numpy.float64'>'
	with 66932 stored elements in Compressed Sparse Row format>>

In [ ]:
df['Score'].value_counts()


Score
60     503
100    492
88     266
84     260
92     236
80     225
96     199
76     167
72     161
68     158
64      86
52      78
56      77
48      66
44      42
40      41
0       37
36      36
28      24
20      23
32      18
24      17
16      13
4       10
8        8
12       8
94       5
90       2
82       1
10       1
98       1
Name: count, dtype: int64

In [22]:
text=["  خوب نبود"]
x=vectorizer.transform(text)
Mn.predict(x)

array([1])

#

In [ ]:
import joblib

joblib.dump(Mn, '/content/sentiment_model.pkl')
joblib.dump(vectorizer, '/content/vectorizer.pkl')


['/content/vectorizer.pkl']

In [ ]:
!pip install gradio
!pip install streamlit


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.9/46.9 MB 27.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.2/322.2 kB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 67.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 51.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 38.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 7.6 MB/s eta 0:00:00


In [ ]:
import streamlit as st
import joblib

# لود کردن مدل و وکتورایزر
model = joblib.load('sentiment_model.pkl')
vectorizer = joblib.load('vectorizer.pkl')

# تابع پیش‌بینی احساس
def predict_sentiment(text):
    vect_text = vectorizer.transform([text])
    prediction = model.predict(vect_text)[0]

    label_map = {
        1: "👍 مثبت",
        0: "🟡 خنثی",
        -1: "👎 منفی"
    }
    return label_map[prediction]

# رابط کاربری
st.title("🔍 تحلیل احساسات نظرات دیجیکالا")
st.write("یک متن وارد کن تا احساسش رو پیش‌بینی کنم:")

user_input = st.text_area("📝 متن نظر:")

if st.button("پیش‌بینی"):
    if user_input.strip():
        result = predict_sentiment(user_input)
        st.success(f"نتیجه: **{result}**")
    else:
        st.warning("لطفاً یک متن وارد کن!")


ModuleNotFoundError: No module named 'streamlit'

In [ ]:


# مدل و vectorizer ذخیره‌شده رو بارگذاری کن
model = joblib.load("sentiment_model.pkl")
vectorizer1 = joblib.load("vectorizer.pkl")
text=[" شما هم بخرید  عالی بود"]
x=vectorizer1.transform(text)
model.predict(x)

array([1])

In [ ]:
import gradio as gr
import joblib  # یا pickle
import re

# مدل و vectorizer ذخیره‌شده رو بارگذاری کن
model = joblib.load("sentiment_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# تابع پردازش متن ورودی و پیش‌بینی احساس
def predict_sentiment(text):
    # پردازش ساده (می‌تونی کامل‌ترش کنی)
    text = re.sub(r'[^\w\s]', '', text)  # حذف علائم نگارشی
    text = text.strip()
    vect_text = vectorizer.transform([text])
    prediction = model.predict(vect_text)[0]
    label_map = {3: "منفی", 2: "خنثی", 1: "مثبت"}
    return label_map[prediction]

# ساخت اینترفیس
iface = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(lines=3, placeholder="نظر خود را وارد کنید..."),
    outputs="text",
    title="تشخیص احساس کامنت‌های دیجیکالا",
    description="یک متن بنویسید و ببینید مدل شما چه احساسی برای آن تشخیص می‌دهد."
)

iface.launch(share=True)  # این 'share=True' باعث میشه لینک عمومی تولید بشه


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://66588f01d44d59a773.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [50]:
!git clone https://github.com/MohammadBeyzaei/digikala_sentiment.git
!cp /content/digikala_sentiment.ipynb digikala_sentiment/
!cp /content/digikala_sentiment.csv digikala_sentiment/


fatal: destination path 'digikala_sentiment' already exists and is not an empty directory.
cp: cannot stat '/content/digikala_sentiment.ipynb': No such file or directory


In [ ]:
%cd my-colab-project
!git config --global user.email "your-email@example.com"
!git config --global user.name "Your Name"

In [ ]:
!git add .
!git commit -m "first commit from Colab"

In [49]:
import os
print(os.getcwd())

/content


In [51]:
!ls /content

digikala_sentiment  digikala_sentiment.csv  sample_data
